CREATE  TABLE Users(
user_id VARCHAR(100) Primary Key,
Name VARCHAR(100) NOT NULL,
user_name VARCHAR(120) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
user_password VARCHAR(100) NOT NULL,
isSent BIT DEFAULT '0',
isDelete BIT DEFAULT '0',
)
